-- Additional Tech Blog Posts Seed Data
INSERT INTO posts (title, slug, excerpt, body, status, primary_category_id, author_id, meta_title, meta_description, publish_date, published_at, reading_time_minutes, featured, timezone, views_count, comments_count) VALUES
('Next.js Fundamentals', 'nextjs-fundamentals', 'Learn the fundamentals of Next.js, the React framework for production.', 'Next.js is a React framework for building fast, server-rendered applications.\n\n**Key Features:**\n- File-based routing\n- SSR & SSG\n- API routes', 'published', 1, 1, 'Next.js Fundamentals', 'Learn the basics of Next.js for production-grade React apps.', NOW(), NOW(), 8, FALSE, 'UTC', 0, 0),
('Mastering Git Rebase', 'mastering-git-rebase', 'A detailed guide to mastering Git rebase for a clean commit history.', 'Git rebase allows you to maintain a linear commit history.\n\n```bash\ngit fetch origin\ngit rebase origin/main\n```', 'published', 1, 1, 'Mastering Git Rebase', 'Understand and apply Git rebase effectively.', NOW(), NOW(), 7, FALSE, 'UTC', 0, 0),
('Building REST APIs with Express.js', 'building-rest-apis-express', 'Step-by-step guide to building RESTful APIs using Express.js.', 'Express.js simplifies server creation in Node.js.\n\n```js\nconst express = require("express");\nconst app = express();\napp.listen(3000);\n```', 'published', 1, 1, 'Building REST APIs with Express.js', 'Learn how to build REST APIs with Node.js and Express.', NOW(), NOW(), 9, FALSE, 'UTC', 0, 0),
('Introduction to GraphQL', 'introduction-to-graphql', 'A beginner-friendly introduction to GraphQL and its benefits over REST.', 'GraphQL provides a flexible alternative to REST APIs.\n\n```graphql\nquery { user { id name } }\n```', 'published', 1, 1, 'Introduction to GraphQL', 'Discover the basics and advantages of GraphQL.', NOW(), NOW(), 10, FALSE, 'UTC', 0, 0),
('Deploying with Docker Compose', 'deploying-with-docker-compose', 'Learn how to use Docker Compose for multi-container app deployment.', 'Docker Compose lets you define and run multi-container applications easily.\n\n```yaml\nservices:\n  web:\n    image: nginx\n```', 'published', 1, 1, 'Deploying with Docker Compose', 'Use Docker Compose for scalable app deployment.', NOW(), NOW(), 8, FALSE, 'UTC', 0, 0),
('Understanding WebSockets', 'understanding-websockets', 'Understand how WebSockets enable real-time communication.', 'WebSockets allow full-duplex communication between client and server.\n\n```js\nconst ws = new WebSocket("ws://example.com");\n```', 'published', 1, 1, 'Understanding WebSockets', 'Real-time communication explained with WebSockets.', NOW(), NOW(), 6, FALSE, 'UTC', 0, 0),
('Intro to Tailwind CSS', 'intro-to-tailwind-css', 'Learn how to build modern UIs quickly with Tailwind CSS.', 'Tailwind CSS is a utility-first framework for building responsive designs fast.\n\n```html\n<div class="p-4 text-blue-500">Hello</div>\n```', 'published', 1, 1, 'Intro to Tailwind CSS', 'Learn to style efficiently with Tailwind CSS.', NOW(), NOW(), 5, FALSE, 'UTC', 0, 0),
('Optimizing React Performance', 'optimizing-react-performance', 'Improve the performance of your React apps with proven techniques.', 'React performance can be improved with memoization, code-splitting, and lazy loading.\n\n```js\nconst MemoComp = React.memo(MyComponent);\n```', 'published', 1, 1, 'Optimizing React Performance', 'Tips and tricks for faster React apps.', NOW(), NOW(), 9, FALSE, 'UTC', 0, 0);
